export const SET_USER_STATE = 'set_user_state'
export const CLEAR_USER_STATE = 'clear_user_state'
export const SET_ROUTES = 'set_routes'
export const SET_PROJECT_INFO = 'set_project_info'
export const CLEAR_PROJECT_INFO = 'clear_project_info'
export const SET_LOADING_STATE = 'set_loading_state'
